#Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - bug/*
  - features/*
  - releases/*
  - sprint/*
  - staging

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "RSADockerHub"
  imageRepository: "clickdna-frontend-stage"
  #containerRegistry: 'dockerhub.rsa.global'
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"
  tag1: "latest"

  # Agent VM image name
  # vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
          #vmImage: BuildAgentProd
          name: "BuildAgentProd"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: "$(imageRepository)"
              command: "build"
              Dockerfile: $(dockerfilePath)
              arguments: '--build-arg api_env="$(CLICKDNAENV)" --build-arg api_url="$(AZURE_BASE_API_URL)" --build-arg api_key="$(AZURE_SUB_KEY)" '
              includeLatestTag: true
              tags: |
                $(tag)
                $(tag1)
          - task: Docker@2
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: "$(imageRepository)"
              command: "push"
              tags: |
                $(tag)
                $(tag1)

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "Kubernetes"
              ArtifactName: "drop"
              publishLocation: "Container"

  - stage: Deploy
    displayName: Deploy in K8s Cluster
    jobs:
      - job: Deploy
        displayName: Helm Deploy
        pool:
          #vmImage: BuildAgentProd
          name: "BuildAgentProd"
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "specific"
              downloadPath: "$(System.ArtifactsDirectory)"

          - task: HelmInstaller@0
            inputs:
              helmVersion: "2.9.1"
              installKubectl: true

          - task: HelmDeploy@0
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'staging'
              namespace: 'clickdna-stage'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(System.ArtifactsDirectory)\drop'
              valueFile: '$(System.ArtifactsDirectory)\drop\values-stage.yaml'
              releaseName: 'clickdna-frontend-stage'
             # arguments: '--dry-run'
             # overrideValues: 'image=dockerhub.rsa.global/clickdna-frontend:staging,replicas=2,hostname=clickdna-dev.rsa.global'
              
         

          
   
          
