version: '3.7'

services:
  clickdna_frontend_dev:
    container_name: clickdna_frontend_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment: 
      - VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}
      - VUE_APP_SUBSCRIPTION_KEY=${VUE_APP_SUBSCRIPTION_KEY}
    volumes:
      - clickdna-node_modules:/app/node_modules
    env_file:
      - development.env
    ports:
      - '8080:8080'
volumes:
  clickdna-node_modules:
