FROM node:14-alpine3.12

# make the 'app' folder the current working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./app/package.json ./

# Upgrading npm version
RUN npm install -g npm@6.14.13

# install project dependencies
RUN npm install .

COPY ./app/entrypoint.sh .

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY ./app .

CMD ["sh", "/app/entrypoint.sh"]
