apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.port }}
    #targetPort: {{ default 80 .Values.port }}
    targetPort: {{ .Values.targetport }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.name }}
  type: NodePort
